import Link from "next/link";
export default function Home() {
  return <main className="landing">
    <header className="landing-nav"><Link className="brand" href="/"><span className="brand-mark" aria-hidden="true">↗</span>ReSource</Link><nav aria-label="Main navigation"><Link href="/dashboard">Dashboard</Link><Link href="/requests">Requests</Link><Link href="/inventory">Inventory</Link><Link className="landing-nav-cta" href="/demo">Explore the demo <span aria-hidden="true">→</span></Link></nav></header>
    <section className="landing-hero"><div className="hero-copy"><p className="eyebrow">A school-community sharing concept</p><h1>Better resources.<br/>Less waste.<br/><span>Stronger schools.</span></h1><p className="landing-lede">ReSource helps schools find useful surplus nearby—so more classroom needs can be met with resources the community already has.</p><div className="hero-actions"><Link className="action-button" href="/demo">Take the 10-step demo <span aria-hidden="true">→</span></Link><Link className="text-link" href="/dashboard">View the sample dashboard</Link></div><p className="match-meta">Student-built concept · all sample schools and data are fictional</p></div><aside className="hero-card"><div className="hero-card-top"><span className="scenario-status">HOW IT WORKS</span><span aria-hidden="true">✳</span></div><div className="hero-journey"><div><span className="journey-icon">01</span><span><strong>A teacher asks</strong><small>Share a classroom need</small></span></div><i aria-hidden="true"/><div><span className="journey-icon">02</span><span><strong>Partners match</strong><small>See compatible surplus</small></span></div><i aria-hidden="true"/><div><span className="journey-icon">03</span><span><strong>Resources move</strong><small>Track a transparent handoff</small></span></div></div><div className="hero-card-note"><span className="hero-dot"/> Designed for clarity, consent, and responsible reuse</div></aside></section>
    <section className="landing-bottom"><div><span className="eyebrow">Built around trust</span><p>Explainable recommendations. Separate provider approvals. Impact figures that say what they actually mean.</p></div><div className="landing-links"><Link href="/requests">Browse sample requests ↗</Link><Link href="/inventory">See sample inventory ↗</Link></div></section>
    <footer className="landing-footer"><Link className="brand" href="/"><span className="brand-mark" aria-hidden="true">↗</span>ReSource</Link><p>Demonstration only · Fictional Fremont-area scenario · No FUSD affiliation claimed</p></footer>
  </main>;
}
